import type { ParticipantRecord, SessionSnapshot } from "@/src/core/types";
import { RaidIcon } from "@/components/icons/RaidIcon";

function initials(name: string) { return name.split(/\s+/).slice(0,2).map((part) => part[0]?.toUpperCase()).join(""); }

export function FormationBoard({ snapshot, canManage, onAssign, onCreateTeam }: { snapshot: SessionSnapshot; canManage: boolean; onAssign: (participantId: string, teamId: string | null) => void; onCreateTeam: (name: string) => void }) {
  const active = snapshot.participants.filter((participant) => participant.role !== "SPECTATOR");
  const unassigned = active.filter((participant) => !participant.teamId);
  return <section className="formation-board material-sheet"><header><div><span className="kicker">Formation du groupe</span><h2>Qui part où&nbsp;?</h2></div><span className="formation-count mono">{snapshot.teams.length} escouades</span></header><div className="formation-lanes">{snapshot.teams.map((team,index)=><TeamLane key={team.id} teamId={team.id} name={team.name} participants={active.filter((participant)=>participant.teamId===team.id)} teams={snapshot.teams} canManage={canManage} onAssign={onAssign} index={index}/>) }{unassigned.length>0&&<TeamLane teamId="" name="À affecter" participants={unassigned} teams={snapshot.teams} canManage={canManage} onAssign={onAssign} index={snapshot.teams.length}/>}</div>{canManage&&<form className="formation-create" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);const name=String(form.get("teamName")??"").trim();if(name){onCreateTeam(name);event.currentTarget.reset();}}}><label className="sr-only" htmlFor="formation-team-name">Nom de la nouvelle équipe</label><input id="formation-team-name" name="teamName" placeholder="Nouvelle escouade" maxLength={80}/><button className="secondary" type="submit"><RaidIcon name="team"/>Créer</button></form>}<div className="arrival-strip"><RaidIcon name="weave"/><strong>Groupe synchronisé</strong><span>Les affectations sont confirmées par le serveur.</span></div></section>;
}

function TeamLane({ teamId, name, participants, teams, canManage, onAssign, index }: { teamId: string; name: string; participants: ParticipantRecord[]; teams: SessionSnapshot["teams"]; canManage: boolean; onAssign: (participantId: string, teamId: string|null)=>void; index:number }) {
  const roleFr: Record<ParticipantRecord["role"],string> = { CAPTAIN:"CAPITAINE",EDITOR:"ÉDITEUR",PARTICIPANT:"PARTICIPANT",SPECTATOR:"SPECTATEUR" };
  return <article className="formation-lane" style={{"--lane-index":index} as React.CSSProperties}><header><h3>{name}</h3><span>{participants.length} joueur{participants.length===1?"":"s"}</span></header>{participants.length?participants.map((participant)=><div className="formation-person" key={participant.id}><span className="formation-avatar">{initials(participant.displayName)}</span><span><strong>{participant.displayName}</strong><small>{roleFr[participant.role]}</small></span><span className={participant.readyState==="READY"?"ready":"not-ready"}>{participant.readyState==="READY"?"PRÊT":"ATTEND"}</span>{canManage&&<select aria-label={`Équipe de ${participant.displayName}`} value={teamId} onChange={(event)=>onAssign(participant.id,event.target.value||null)}><option value="">Sans équipe</option>{teams.map((team)=><option key={team.id} value={team.id}>{team.name}</option>)}</select>}</div>):<div className="formation-empty">Place libre · aucune personne affectée</div>}</article>;
}
